data:
  db_path: "data/gas_monitoring.db"
  table_name: "gas_monitoring"

preprocessing:
  temp_lower_bound: 12.59
  temp_upper_bound: 29.52
  humidity_lower_bound: 10.0
  humidity_upper_bound: 90.0

model:
  algorithm: "DecisionTree"
  test_size: 0.2
  random_state: 42